export const games = [
  {
    number: 1,
    date: "May 13th",
    versus: "vs. Leffs Lucky Town",
    result: "W",
    time: "7:00",
    field: "#1",
    score: ", 11-18",
    opponent: "Leffs Lucky Town",
    home: true,
    allstateScore: 18,
    opponentScore: 11,
    runs: [
      {
        allstate: 2,
        opponent: 6,
      },
      {
        allstate: 5,
        opponent: 2,
      },
      {
        allstate: 0,
        opponent: 2,
      },
      {
        allstate: 11,
        opponent: 1,
      },
      {
        allstate: 0,
        opponent: 0,
      },
      {
        allstate: 0,
        opponent: 0,
      },
      {
        allstate: "-",
        opponent: "-",
      },
    ],
  },
  {
    number: 2,
    date: "May 20th",
    versus: "vs. Team Sluggos",
    result: "W",
    time: "6:00",
    field: "#3",
    score: ", 4-11",
    opponent: "Team Sluggos",
    home: false,
    allstateScore: 11,
    opponentScore: 4,
    runs: [
      {
        allstate: 2,
        opponent: 0,
      },
      {
        allstate: 1,
        opponent: 0,
      },
      {
        allstate: 2,
        opponent: 3,
      },
      {
        allstate: 3,
        opponent: 0,
      },
      {
        allstate: 3,
        opponent: 0,
      },
      {
        allstate: 0,
        opponent: 1,
      },
      {
        allstate: 0,
        opponent: 0,
      },
    ],
  },
  {
    number: 3,
    date: "May 27th",
    versus: "vs. Junky Stars",
    result: "Postponed",
    time: "6:00",
    field: "#1",
    score: "",
    opponent: "Junky Stars",
    home: true,
  },
  {
    number: 4,
    date: "June 3rd",
    versus: "vs. Milliman",
    result: "L",
    time: "6:00",
    field: "#3",
    score: ", 20-4",
    opponent: "Milliman",
    home: false,
    allstateScore: 4,
    opponentScore: 20,
    runs: [
      {
        allstate: 1,
        opponent: 0,
      },
      {
        allstate: 0,
        opponent: 2,
      },
      {
        allstate: 2,
        opponent: 6,
      },
      {
        allstate: 0,
        opponent: 8,
      },
      {
        allstate: 0,
        opponent: 3,
      },
      {
        allstate: 1,
        opponent: 1,
      },
      {
        allstate: 0,
        opponent: "-",
      },
    ],
  },
  {
    number: 5,
    date: "June 10th",
    versus: "vs. Team Charter",
    result: "L",
    time: "9:00",
    field: "#1",
    score: ", 15-14",
    opponent: "Team Charter",
    home: true,
    allstateScore: 14,
    opponentScore: 15,
    runs: [
      {
        allstate: 4,
        opponent: 0,
      },
      {
        allstate: 0,
        opponent: 7,
      },
      {
        allstate: 2,
        opponent: 3,
      },
      {
        allstate: 6,
        opponent: 1,
      },
      {
        allstate: 1,
        opponent: 4,
      },
      {
        allstate: 1,
        opponent: 0,
      },
      {
        allstate: "-",
        opponent: "-",
      },
    ],
  },
  {
    number: 6,
    date: "June 17th",
    versus: "vs. Pizza Man",
    result: "L",
    time: "6:00",
    field: "#2",
    score: ", 19-8",
    opponent: "Pizza Man",
    home: false,
    allstateScore: 8,
    opponentScore: 19,
    runs: [
      {
        allstate: 2,
        opponent: 3,
      },
      {
        allstate: 2,
        opponent: 2,
      },
      {
        allstate: 0,
        opponent: 0,
      },
      {
        allstate: 0,
        opponent: 9,
      },
      {
        allstate: 0,
        opponent: 5,
      },
      {
        allstate: 4,
        opponent: 0,
      },
      {
        allstate: "-",
        opponent: "-",
      },
    ],
  },
  {
    number: 7,
    date: "June 24th",
    versus: "vs. Sluggos Sluggers",
    result: "Postponed",
    time: "7:00",
    field: "#1",
    score: "",
    opponent: "Sluggos Sluggers",
    home: true,
  },
  {
    number: 8,
    date: "July 1st",
    versus: "vs. Leffs Lucky Town",
    result: "L",
    time: "7:00",
    field: "#2",
    score: ", 19-4",
    opponent: "Leffs Lucky Town",
    home: false,
    allstateScore: 4,
    opponentScore: 19,
    runs: [
      {
        allstate: 4,
        opponent: 3,
      },
      {
        allstate: 0,
        opponent: 2,
      },
      {
        allstate: 0,
        opponent: 2,
      },
      {
        allstate: 0,
        opponent: 3,
      },
      {
        allstate: 0,
        opponent: 8,
      },
      {
        allstate: 0,
        opponent: 1,
      },
      {
        allstate: 0,
        opponent: "-",
      },
    ],
  },
  {
    number: 9,
    date: "July 8th",
    versus: "vs. Team Sluggos",
    result: "L",
    time: "8:00",
    field: "#1",
    score: ", 13-12",
    opponent: "Team Sluggos",
    home: true,
    allstateScore: 12,
    opponentScore: 13,
    runs: [
      {
        allstate: 1,
        opponent: 1,
      },
      {
        allstate: 0,
        opponent: 4,
      },
      {
        allstate: 5,
        opponent: 2,
      },
      {
        allstate: 2,
        opponent: 1,
      },
      {
        allstate: 0,
        opponent: 4,
      },
      {
        allstate: 4,
        opponent: 1,
      },
      {
        allstate: "-",
        opponent: "-",
      },
    ],
  },
  {
    number: 10,
    date: "July 15th",
    versus: "vs. Junky Stars",
    result: "",
    time: "7:00",
    field: "#2",
    score: "",
    opponent: "Junky Stars",
  },
  {
    number: 11,
    date: "July 22nd",
    versus: "vs. Milliman",
    result: "",
    time: "6:00",
    field: "#1",
    score: "",
    opponent: "Milliman",
  },
  {
    number: 12,
    date: "July 29th",
    versus: "vs. Team Charter",
    result: "",
    time: "6:00",
    field: "#2",
    score: "",
    opponent: "Team Charter",
  },
  {
    number: 13,
    date: "August 5th",
    versus: "vs. Pizza Man",
    result: "",
    time: "7:00",
    field: "#1",
    score: "",
    opponent: "Pizza Man",
  },
  {
    number: 14,
    date: "August 12th",
    versus: "vs. TBD",
    result: "",
    time: "TBD",
    field: "TBD",
    score: "",
    opponent: "",
  },
];
