export const gameStats = [
  {
    game: 1,
    playerStats: [
      {
        name: "Jason Fuchs",
        atBats: "5",
        runs: "3",
        hits: "3",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "1",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Elijah Goodman",
        atBats: "4",
        runs: "4",
        hits: "4",
        doubles: "1",
        triples: "0",
        homeruns: "1",
        runsBattedIn: "3",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Matt Ausloos",
        atBats: "4",
        runs: "3",
        hits: "4",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "5",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Jon Keane",
        atBats: "4",
        runs: "1",
        hits: "4",
        doubles: "1",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "4",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Donny Baseball",
        atBats: "4",
        runs: "1",
        hits: "1",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "0",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Josh Serio",
        atBats: "4",
        runs: "0",
        hits: "0",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "0",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Avery Goodman",
        atBats: "3",
        runs: "1",
        hits: "1",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "1",
        baseOnBalls: "1",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Matt Goetz",
        atBats: "4",
        runs: "2",
        hits: "2",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "1",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Steve Nelsen",
        atBats: "4",
        runs: "1",
        hits: "3",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "2",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Dennis Vavrik",
        atBats: "1",
        runs: "0",
        hits: "0",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "1",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Kelly Goodman",
        atBats: "3",
        runs: "2",
        hits: "2",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "0",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
    ],
  },
  {
    game: 2,
    playerStats: [
      {
        name: "Jason Fuchs",
        atBats: "5",
        runs: "1",
        hits: "2",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "0",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Elijah Goodman",
        atBats: "5",
        runs: "2",
        hits: "4",
        doubles: "0",
        triples: "0",
        homeruns: "1",
        runsBattedIn: "4",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Matt Ausloos",
        atBats: "4",
        runs: "1",
        hits: "2",
        doubles: "1",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "1",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Jon Keane",
        atBats: "4",
        runs: "1",
        hits: "4",
        doubles: "0",
        triples: "0",
        homeruns: "1",
        runsBattedIn: "3",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Donny Baseball",
        atBats: "3",
        runs: "0",
        hits: "0",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "0",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Josh Serio",
        atBats: "4",
        runs: "1",
        hits: "2",
        doubles: "0",
        triples: "0",
        homeruns: "1",
        runsBattedIn: "2",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Rick Steinberg",
        atBats: "3",
        runs: "0",
        hits: "0",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "0",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Matt Goetz",
        atBats: "4",
        runs: "1",
        hits: "2",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "0",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Steve Nelsen",
        atBats: "4",
        runs: "3",
        hits: "3",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "0",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Dennis Vavrik",
        atBats: "2",
        runs: "0",
        hits: "1",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "0",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Kelly Goodman",
        atBats: "2",
        runs: "0",
        hits: "0",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "0",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Jim Fuchs",
        atBats: "1",
        runs: "0",
        hits: "0",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "0",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Avery Goodman",
        atBats: "2",
        runs: "1",
        hits: "1",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "1",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
    ],
  },
  {
    game: 4,
    playerStats: [
      {
        name: "Jason Fuchs",
        atBats: "4",
        runs: "1",
        hits: "2",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "0",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Elijah Goodman",
        atBats: "4",
        runs: "1",
        hits: "2",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "0",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Matt Ausloos",
        atBats: "4",
        runs: "1",
        hits: "1",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "0",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Jon Keane",
        atBats: "3",
        runs: "0",
        hits: "0",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "0",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Steve Nelsen",
        atBats: "3",
        runs: "0",
        hits: "1",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "2",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Josh Serio",
        atBats: "3",
        runs: "1",
        hits: "2",
        doubles: "1",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "1",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Avery Goodman",
        atBats: "3",
        runs: "0",
        hits: "2",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "0",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Matt Goetz",
        atBats: "2",
        runs: "0",
        hits: "0",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "1",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "1",
      },
      {
        name: "Dennis Vavrik",
        atBats: "3",
        runs: "0",
        hits: "1",
        doubles: "1",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "0",
        baseOnBalls: "0",
        strikeouts: "1",
        sac: "0",
      },
      {
        name: "Jim Fuchs",
        atBats: "2",
        runs: "0",
        hits: "0",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "0",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Kelly Goodman",
        atBats: "1",
        runs: "0",
        hits: "1",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "0",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
    ],
  },
  {
    game: 5,
    playerStats: [
      {
        name: "Jason Fuchs",
        atBats: "5",
        runs: "2",
        hits: "4",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "0",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Elijah Goodman",
        atBats: "5",
        runs: "3",
        hits: "3",
        doubles: "1",
        triples: "0",
        homeruns: "1",
        runsBattedIn: "2",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Matt Ausloos",
        atBats: "4",
        runs: "2",
        hits: "1",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "1",
        baseOnBalls: "1",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Jon Keane",
        atBats: "3",
        runs: "2",
        hits: "3",
        doubles: "2",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "1",
        baseOnBalls: "1",
        strikeouts: "0",
        sac: "1",
      },
      {
        name: "Avery Goodman",
        atBats: "4",
        runs: "2",
        hits: "2",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "1",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "1",
      },
      {
        name: "Josh Serio",
        atBats: "3",
        runs: "1",
        hits: "2",
        doubles: "1",
        triples: "0",
        homeruns: "1",
        runsBattedIn: "6",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "1",
      },
      {
        name: "Kelly Goodman",
        atBats: "3",
        runs: "0",
        hits: "3",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "0",
        baseOnBalls: "1",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Donny Baseball",
        atBats: "4",
        runs: "1",
        hits: "3",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "1",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Dennis Vavrik",
        atBats: "4",
        runs: "0",
        hits: "0",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "1",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Jim Fuchs",
        atBats: "3",
        runs: "1",
        hits: "1",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "1",
        baseOnBalls: "0",
        strikeouts: "2",
        sac: "0",
      },
    ],
  },
  {
    game: 6,
    playerStats: [
      {
        name: "Jason Fuchs",
        atBats: "3",
        runs: "2",
        hits: "2",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "1",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "1",
      },
      {
        name: "Matt Ausloos",
        atBats: "4",
        runs: "2",
        hits: "3",
        doubles: "1",
        triples: "1",
        homeruns: "0",
        runsBattedIn: "1",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Steve Nelsen",
        atBats: "4",
        runs: "1",
        hits: "1",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "2",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Matt Goetz",
        atBats: "4",
        runs: "0",
        hits: "1",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "1",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Donny Baseball",
        atBats: "3",
        runs: "0",
        hits: "0",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "0",
        baseOnBalls: "1",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Matthew Liewen",
        atBats: "4",
        runs: "1",
        hits: "2",
        doubles: "1",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "0",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Avery Goodman",
        atBats: "4",
        runs: "1",
        hits: "3",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "2",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Dennis Vavrik",
        atBats: "3",
        runs: "1",
        hits: "0",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "0",
        baseOnBalls: "1",
        strikeouts: "2",
        sac: "0",
      },
      {
        name: "Kelly Goodman",
        atBats: "2",
        runs: "0",
        hits: "2",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "0",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Sam Botbol",
        atBats: "3",
        runs: "0",
        hits: "1",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "1",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Bob 'Truth' Goetz",
        atBats: "1",
        runs: "0",
        hits: "0",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "0",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
    ],
  },
  {
    game: 8,
    playerStats: [
      {
        name: "Jason Fuchs",
        atBats: "4",
        runs: "0",
        hits: "3",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "0",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Kelly Goodman",
        atBats: "4",
        runs: "0",
        hits: "2",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "0",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Matt Ausloos",
        atBats: "4",
        runs: "1",
        hits: "1",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "0",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Jon Keane",
        atBats: "4",
        runs: "1",
        hits: "2",
        doubles: "1",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "0",
        baseOnBalls: "0",
        strikeouts: "1",
        sac: "0",
      },
      {
        name: "Avery Goodman",
        atBats: "4",
        runs: "1",
        hits: "2",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "1",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Steve Nelsen",
        atBats: "4",
        runs: "1",
        hits: "2",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "0",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Seth Nelsen",
        atBats: "3",
        runs: "0",
        hits: "2",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "1",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Donny Baseball",
        atBats: "3",
        runs: "0",
        hits: "3",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "1",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Rick Steinberg",
        atBats: "2",
        runs: "0",
        hits: "0",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "1",
        baseOnBalls: "1",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Jim Fuchs",
        atBats: "3",
        runs: "0",
        hits: "0",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "0",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
    ],
  },
  {
    game: 9,
    playerStats: [
      {
        name: "Jason Fuchs",
        atBats: "4",
        runs: "1",
        hits: "1",
        doubles: "0",
        triples: "1",
        homeruns: "0",
        runsBattedIn: "0",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Elijah Goodman",
        atBats: "4",
        runs: "2",
        hits: "4",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "1",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Matt Ausloos",
        atBats: "4",
        runs: "3",
        hits: "2",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "1",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Jon Keane",
        atBats: "3",
        runs: "2",
        hits: "2",
        doubles: "1",
        triples: "0",
        homeruns: "1",
        runsBattedIn: "4",
        baseOnBalls: "1",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Steve Nelsen",
        atBats: "4",
        runs: "2",
        hits: "3",
        doubles: "1",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "2",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Kelly Goodman",
        atBats: "4",
        runs: "1",
        hits: "2",
        doubles: "1",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "1",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Avery Goodman",
        atBats: "4",
        runs: "0",
        hits: "3",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "2",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Andrew Bruggink",
        atBats: "3",
        runs: "0",
        hits: "2",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "1",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "1",
      },
      {
        name: "Dennis Vavrik",
        atBats: "4",
        runs: "0",
        hits: "0",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "0",
        baseOnBalls: "0",
        strikeouts: "1",
        sac: "0",
      },
      {
        name: "Jim Fuchs",
        atBats: "3",
        runs: "1",
        hits: "0",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "0",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
    ],
  },
  {
    game: 10,
    playerStats: [
      {
        name: "Jason Fuchs",
        atBats: "5",
        runs: "2",
        hits: "1",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "0",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Matt Ausloos",
        atBats: "5",
        runs: "4",
        hits: "4",
        doubles: "1",
        triples: "1",
        homeruns: "0",
        runsBattedIn: "0",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Elijah Goodman",
        atBats: "5",
        runs: "3",
        hits: "4",
        doubles: "1",
        triples: "0",
        homeruns: "1",
        runsBattedIn: "3",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Jon Keane",
        atBats: "4",
        runs: "4",
        hits: "4",
        doubles: "3",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "5",
        baseOnBalls: "1",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Josh Serio",
        atBats: "5",
        runs: "2",
        hits: "4",
        doubles: "0",
        triples: "0",
        homeruns: "1",
        runsBattedIn: "3",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Avery Goodman",
        atBats: "3",
        runs: "0",
        hits: "1",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "1",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Steve Nelsen",
        atBats: "4",
        runs: "0",
        hits: "2",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "0",
        baseOnBalls: "1",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Donny Baseball",
        atBats: "5",
        runs: "0",
        hits: "1",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "2",
        baseOnBalls: "0",
        strikeouts: "1",
        sac: "0",
      },
      {
        name: "Matt Goetz",
        atBats: "4",
        runs: "0",
        hits: "2",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "0",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Dennis Vavrik",
        atBats: "2",
        runs: "0",
        hits: "0",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "0",
        baseOnBalls: "1",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Kelly Goodman",
        atBats: "1",
        runs: "0",
        hits: "0",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "1",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "1",
      },
      {
        name: "Jim Fuchs",
        atBats: "1",
        runs: "0",
        hits: "0",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "0",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
    ],
  },
  {
    game: 11,
    playerStats: [
      {
        name: "Jason Fuchs",
        atBats: "4",
        runs: "1",
        hits: "1",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "2",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Jon Keane",
        atBats: "3",
        runs: "2",
        hits: "1",
        doubles: "0",
        triples: "0",
        homeruns: "1",
        runsBattedIn: "1",
        baseOnBalls: "1",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Elijah Goodman",
        atBats: "3",
        runs: "2",
        hits: "2",
        doubles: "0",
        triples: "0",
        homeruns: "1",
        runsBattedIn: "2",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "1",
      },
      {
        name: "Josh Serio",
        atBats: "4",
        runs: "0",
        hits: "3",
        doubles: "1",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "1",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Andrew Bruggink",
        atBats: "2",
        runs: "0",
        hits: "0",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "1",
        baseOnBalls: "1",
        strikeouts: "0",
        sac: "1",
      },
      {
        name: "Steve Nelsen",
        atBats: "3",
        runs: "1",
        hits: "1",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "1",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "1",
      },
      {
        name: "Donny Baseball",
        atBats: "3",
        runs: "1",
        hits: "1",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "0",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Kelly Goodman",
        atBats: "3",
        runs: "1",
        hits: "1",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "0",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Rick Steinberg",
        atBats: "3",
        runs: "1",
        hits: "1",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "1",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Jim Fuchs",
        atBats: "3",
        runs: "1",
        hits: "1",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "1",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
    ],
  },
  {
    game: 12,
    playerStats: [
      {
        name: "Avery Goodman",
        atBats: "5",
        runs: "1",
        hits: "2",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "0",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Austin",
        atBats: "5",
        runs: "2",
        hits: "2",
        doubles: "0",
        triples: "0",
        homeruns: "2",
        runsBattedIn: "4",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Elijah Goodman",
        atBats: "5",
        runs: "3",
        hits: "5",
        doubles: "0",
        triples: "0",
        homeruns: "2",
        runsBattedIn: "3",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Josh Serio",
        atBats: "5",
        runs: "2",
        hits: "2",
        doubles: "0",
        triples: "0",
        homeruns: "1",
        runsBattedIn: "1",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Steve Nelsen",
        atBats: "4",
        runs: "1",
        hits: "3",
        doubles: "1",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "2",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Gunnar Malensak",
        atBats: "4",
        runs: "0",
        hits: "1",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "0",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Jason Fuchs",
        atBats: "4",
        runs: "1",
        hits: "2",
        doubles: "0",
        triples: "1",
        homeruns: "0",
        runsBattedIn: "1",
        baseOnBalls: "0",
        strikeouts: "1",
        sac: "0",
      },
      {
        name: "Rick Steinberg",
        atBats: "4",
        runs: "0",
        hits: "3",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "1",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Dennis Vavrik",
        atBats: "4",
        runs: "0",
        hits: "0",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "0",
        baseOnBalls: "0",
        strikeouts: "3",
        sac: "0",
      },
      {
        name: "Jim Fuchs",
        atBats: "2",
        runs: "1",
        hits: "1",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "0",
        baseOnBalls: "0",
        strikeouts: "1",
        sac: "0",
      },
      {
        name: "Kelly Goodman",
        atBats: "2",
        runs: "1",
        hits: "1",
        doubles: "1",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "0",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
    ],
  },
  {
    game: 13,
    playerStats: [
      {
        name: "Avery Goodman",
        atBats: "4",
        runs: "0",
        hits: "1",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "1",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Matt Ausloos",
        atBats: "4",
        runs: "2",
        hits: "3",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "0",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Elijah Goodman",
        atBats: "2",
        runs: "3",
        hits: "2",
        doubles: "0",
        triples: "0",
        homeruns: "2",
        runsBattedIn: "4",
        baseOnBalls: "1",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Jon Keane",
        atBats: "4",
        runs: "3",
        hits: "3",
        doubles: "2",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "0",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Josh Serio",
        atBats: "4",
        runs: "1",
        hits: "3",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "0",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Jason Fuchs",
        atBats: "4",
        runs: "2",
        hits: "3",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "4",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Steve Nelsen",
        atBats: "4",
        runs: "2",
        hits: "2",
        doubles: "1",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "2",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Donny Baseball",
        atBats: "4",
        runs: "0",
        hits: "1",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "1",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Kelly Goodman",
        atBats: "3",
        runs: "1",
        hits: "3",
        doubles: "1",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "2",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Dennis Vavrik",
        atBats: "3",
        runs: "0",
        hits: "1",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "0",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
    ],
  },
  {
    game: 14,
    playerStats: [
      {
        name: "Matt Goetz",
        atBats: "4",
        runs: "4",
        hits: "3",
        doubles: "0",
        triples: "0",
        homeruns: "3",
        runsBattedIn: "4",
        baseOnBalls: "1",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Matt Ausloos",
        atBats: "4",
        runs: "3",
        hits: "3",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "0",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Elijah Goodman",
        atBats: "4",
        runs: "2",
        hits: "2",
        doubles: "0",
        triples: "0",
        homeruns: "1",
        runsBattedIn: "2",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Jon Keane",
        atBats: "4",
        runs: "3",
        hits: "4",
        doubles: "1",
        triples: "0",
        homeruns: "2",
        runsBattedIn: "5",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Josh Serio",
        atBats: "3",
        runs: "2",
        hits: "3",
        doubles: "0",
        triples: "0",
        homeruns: "2",
        runsBattedIn: "4",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "1",
      },
      {
        name: "Jason Fuchs",
        atBats: "4",
        runs: "1",
        hits: "1",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "0",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Steve Nelsen",
        atBats: "4",
        runs: "0",
        hits: "1",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "0",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Kelly Goodman",
        atBats: "2",
        runs: "0",
        hits: "1",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "1",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Donny Baseball",
        atBats: "4",
        runs: "1",
        hits: "2",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "0",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Rick Steinberg",
        atBats: "4",
        runs: "0",
        hits: "0",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "0",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Jim Fuchs",
        atBats: "2",
        runs: "0",
        hits: "1",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "0",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
    ],
  },
  {
    game: 15,
    playerStats: [
      {
        name: "Matt Goetz",
        atBats: "5",
        runs: "2",
        hits: "1",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "0",
        baseOnBalls: "1",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Matt Ausloos",
        atBats: "6",
        runs: "2",
        hits: "3",
        doubles: "0",
        triples: "1",
        homeruns: "0",
        runsBattedIn: "1",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Elijah Goodman",
        atBats: "5",
        runs: "2",
        hits: "4",
        doubles: "0",
        triples: "0",
        homeruns: "1",
        runsBattedIn: "2",
        baseOnBalls: "1",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Josh Serio",
        atBats: "5",
        runs: "2",
        hits: "4",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "3",
        baseOnBalls: "1",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Michael Barnes",
        atBats: "6",
        runs: "1",
        hits: "3",
        doubles: "1",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "1",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Jason Fuchs",
        atBats: "4",
        runs: "2",
        hits: "2",
        doubles: "1",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "1",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "1",
      },
      {
        name: "Steve Nelsen",
        atBats: "6",
        runs: "0",
        hits: "1",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "1",
        baseOnBalls: "0",
        strikeouts: "1",
        sac: "0",
      },
      {
        name: "Avery Goodman",
        atBats: "6",
        runs: "0",
        hits: "1",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "1",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Donny Baseball",
        atBats: "6",
        runs: "1",
        hits: "4",
        doubles: "1",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "2",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Rick Steinberg",
        atBats: "3",
        runs: "0",
        hits: "1",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "0",
        baseOnBalls: "0",
        strikeouts: "0",
        sac: "0",
      },
      {
        name: "Kelly Goodman",
        atBats: "1",
        runs: "0",
        hits: "0",
        doubles: "0",
        triples: "0",
        homeruns: "0",
        runsBattedIn: "0",
        baseOnBalls: "1",
        strikeouts: "0",
        sac: "0",
      },
    ],
  },
];
