export const gameStats = [
    {
        game: 1,
        playerStats: [
            {
                name: 'Jason Fuchs',
                atBats: '5',
                runs: '3',
                hits: '3',
                doubles: '0',
                triples: '0',
                homeruns: '0',
                runsBattedIn: '1',
                baseOnBalls: '0',
                strikeouts: '0',
                sac: '0',
            },
            {
                name: 'Elijah Goodman',
                atBats: '4',
                runs: '4',
                hits: '4',
                doubles: '1',
                triples: '0',
                homeruns: '1',
                runsBattedIn: '3',
                baseOnBalls: '0',
                strikeouts: '0',
                sac: '0',
            },
            {
                name: 'Matt Ausloos',
                atBats: '4',
                runs: '3',
                hits: '4',
                doubles: '0',
                triples: '0',
                homeruns: '0',
                runsBattedIn: '5',
                baseOnBalls: '0',
                strikeouts: '0',
                sac: '0',
            },
            {
                name: 'Jon Keane',
                atBats: '4',
                runs: '1',
                hits: '4',
                doubles: '1',
                triples: '0',
                homeruns: '0',
                runsBattedIn: '4',
                baseOnBalls: '0',
                strikeouts: '0',
                sac: '0',
            },
            {
                name: 'Donny Baseball',
                atBats: '4',
                runs: '1',
                hits: '1',
                doubles: '0',
                triples: '0',
                homeruns: '0',
                runsBattedIn: '0',
                baseOnBalls: '0',
                strikeouts: '0',
                sac: '0',
            },
            {
                name: 'Josh Serio',
                atBats: '4',
                runs: '0',
                hits: '0',
                doubles: '0',
                triples: '0',
                homeruns: '0',
                runsBattedIn: '0',
                baseOnBalls: '0',
                strikeouts: '0',
                sac: '0',
            },
            {
                name: 'Avery Goodman',
                atBats: '3',
                runs: '1',
                hits: '1',
                doubles: '0',
                triples: '0',
                homeruns: '0',
                runsBattedIn: '1',
                baseOnBalls: '1',
                strikeouts: '0',
                sac: '0',
            },
            {
                name: 'Matt Goetz',
                atBats: '4',
                runs: '2',
                hits: '2',
                doubles: '0',
                triples: '0',
                homeruns: '0',
                runsBattedIn: '1',
                baseOnBalls: '0',
                strikeouts: '0',
                sac: '0',
            },
            {
                name: 'Steve Nelsen',
                atBats: '4',
                runs: '1',
                hits: '3',
                doubles: '0',
                triples: '0',
                homeruns: '0',
                runsBattedIn: '2',
                baseOnBalls: '0',
                strikeouts: '0',
                sac: '0',
            },
            {
                name: 'Dennis Vavrik',
                atBats: '1',
                runs: '0',
                hits: '0',
                doubles: '0',
                triples: '0',
                homeruns: '0',
                runsBattedIn: '1',
                baseOnBalls: '0',
                strikeouts: '0',
                sac: '0',
            },
            {
                name: 'Kelly Goodman',
                atBats: '3',
                runs: '2',
                hits: '2',
                doubles: '0',
                triples: '0',
                homeruns: '0',
                runsBattedIn: '0',
                baseOnBalls: '0',
                strikeouts: '0',
                sac: '0',
            },
        ]
    },
    {
        game: 2,
        playerStats: [
            {
                name: 'Jason Fuchs',
                atBats: '5',
                runs: '1',
                hits: '2',
                doubles: '0',
                triples: '0',
                homeruns: '0',
                runsBattedIn: '0',
                baseOnBalls: '0',
                strikeouts: '0',
                sac: '0',
            },
            {
                name: 'Elijah Goodman',
                atBats: '5',
                runs: '2',
                hits: '4',
                doubles: '0',
                triples: '0',
                homeruns: '1',
                runsBattedIn: '4',
                baseOnBalls: '0',
                strikeouts: '0',
                sac: '0',
            },
            {
                name: 'Matt Ausloos',
                atBats: '4',
                runs: '1',
                hits: '2',
                doubles: '1',
                triples: '0',
                homeruns: '0',
                runsBattedIn: '1',
                baseOnBalls: '0',
                strikeouts: '0',
                sac: '0',
            },
            {
                name: 'Jon Keane',
                atBats: '4',
                runs: '1',
                hits: '4',
                doubles: '0',
                triples: '0',
                homeruns: '0',
                runsBattedIn: '3',
                baseOnBalls: '0',
                strikeouts: '0',
                sac: '0',
            },
            {
                name: 'Donny Baseball',
                atBats: '3',
                runs: '0',
                hits: '0',
                doubles: '0',
                triples: '0',
                homeruns: '0',
                runsBattedIn: '0',
                baseOnBalls: '0',
                strikeouts: '0',
                sac: '0',
            },
            {
                name: 'Josh Serio',
                atBats: '4',
                runs: '1',
                hits: '2',
                doubles: '0',
                triples: '0',
                homeruns: '1',
                runsBattedIn: '2',
                baseOnBalls: '0',
                strikeouts: '0',
                sac: '0',
            },
            {
                name: 'Rick Steinberg',
                atBats: '3',
                runs: '0',
                hits: '0',
                doubles: '0',
                triples: '0',
                homeruns: '0',
                runsBattedIn: '0',
                baseOnBalls: '0',
                strikeouts: '0',
                sac: '0',
            },
            {
                name: 'Matt Goetz',
                atBats: '4',
                runs: '1',
                hits: '2',
                doubles: '0',
                triples: '0',
                homeruns: '0',
                runsBattedIn: '0',
                baseOnBalls: '0',
                strikeouts: '0',
                sac: '0',
            },
            {
                name: 'Steve Nelsen',
                atBats: '4',
                runs: '3',
                hits: '3',
                doubles: '0',
                triples: '0',
                homeruns: '0',
                runsBattedIn: '0',
                baseOnBalls: '0',
                strikeouts: '0',
                sac: '0',
            },
            {
                name: 'Dennis Vavrik',
                atBats: '2',
                runs: '0',
                hits: '1',
                doubles: '0',
                triples: '0',
                homeruns: '0',
                runsBattedIn: '0',
                baseOnBalls: '0',
                strikeouts: '0',
                sac: '0',
            },
            {
                name: 'Kelly Goodman',
                atBats: '2',
                runs: '0',
                hits: '0',
                doubles: '0',
                triples: '0',
                homeruns: '0',
                runsBattedIn: '0',
                baseOnBalls: '0',
                strikeouts: '0',
                sac: '0',
            },
            {
                name: 'Jim Fuchs',
                atBats: '1',
                runs: '0',
                hits: '0',
                doubles: '0',
                triples: '0',
                homeruns: '0',
                runsBattedIn: '0',
                baseOnBalls: '0',
                strikeouts: '0',
                sac: '0',
            },
            {
                name: 'Avery Goodman',
                atBats: '2',
                runs: '1',
                hits: '1',
                doubles: '0',
                triples: '0',
                homeruns: '0',
                runsBattedIn: '1',
                baseOnBalls: '0',
                strikeouts: '0',
                sac: '0',
            },
        ]
    },
    {
        game: 4,
        playerStats: [
            {
                name: 'Jason Fuchs',
                atBats: '4',
                runs: '1',
                hits: '2',
                doubles: '0',
                triples: '0',
                homeruns: '0',
                runsBattedIn: '0',
                baseOnBalls: '0',
                strikeouts: '0',
                sac: '0',
            },
            {
                name: 'Elijah Goodman',
                atBats: '4',
                runs: '1',
                hits: '2',
                doubles: '0',
                triples: '0',
                homeruns: '0',
                runsBattedIn: '0',
                baseOnBalls: '0',
                strikeouts: '0',
                sac: '0',
            },
            {
                name: 'Matt Ausloos',
                atBats: '4',
                runs: '1',
                hits: '1',
                doubles: '0',
                triples: '0',
                homeruns: '0',
                runsBattedIn: '0',
                baseOnBalls: '0',
                strikeouts: '0',
                sac: '0',
            },
            {
                name: 'Jon Keane',
                atBats: '3',
                runs: '0',
                hits: '0',
                doubles: '0',
                triples: '0',
                homeruns: '0',
                runsBattedIn: '0',
                baseOnBalls: '0',
                strikeouts: '0',
                sac: '0',
            },
            {
                name: 'Steve Nelsen',
                atBats: '3',
                runs: '0',
                hits: '1',
                doubles: '0',
                triples: '0',
                homeruns: '0',
                runsBattedIn: '2',
                baseOnBalls: '0',
                strikeouts: '0',
                sac: '0',
            },
            {
                name: 'Josh Serio',
                atBats: '3',
                runs: '1',
                hits: '2',
                doubles: '1',
                triples: '0',
                homeruns: '0',
                runsBattedIn: '1',
                baseOnBalls: '0',
                strikeouts: '0',
                sac: '0',
            },
            {
                name: 'Avery Goodman',
                atBats: '3',
                runs: '0',
                hits: '2',
                doubles: '0',
                triples: '0',
                homeruns: '0',
                runsBattedIn: '0',
                baseOnBalls: '0',
                strikeouts: '0',
                sac: '0',
            },
            {
                name: 'Matt Goetz',
                atBats: '2',
                runs: '0',
                hits: '0',
                doubles: '0',
                triples: '0',
                homeruns: '0',
                runsBattedIn: '1',
                baseOnBalls: '0',
                strikeouts: '0',
                sac: '1',
            },
            {
                name: 'Dennis Vavrik',
                atBats: '3',
                runs: '0',
                hits: '1',
                doubles: '1',
                triples: '0',
                homeruns: '0',
                runsBattedIn: '0',
                baseOnBalls: '0',
                strikeouts: '1',
                sac: '0',
            },
            {
                name: 'Jim Fuchs',
                atBats: '2',
                runs: '0',
                hits: '0',
                doubles: '0',
                triples: '0',
                homeruns: '0',
                runsBattedIn: '0',
                baseOnBalls: '0',
                strikeouts: '0',
                sac: '0',
            },
            {
                name: 'Kelly Goodman',
                atBats: '1',
                runs: '0',
                hits: '1',
                doubles: '0',
                triples: '0',
                homeruns: '0',
                runsBattedIn: '0',
                baseOnBalls: '0',
                strikeouts: '0',
                sac: '0',
            },
        ]
    },
    {
        game: 5,
        playerStats: [
            {
                name: 'Jason Fuchs',
                atBats: '5',
                runs: '2',
                hits: '4',
                doubles: '0',
                triples: '0',
                homeruns: '0',
                runsBattedIn: '0',
                baseOnBalls: '0',
                strikeouts: '0',
                sac: '0',
            },
            {
                name: 'Elijah Goodman',
                atBats: '5',
                runs: '3',
                hits: '3',
                doubles: '1',
                triples: '0',
                homeruns: '1',
                runsBattedIn: '2',
                baseOnBalls: '0',
                strikeouts: '0',
                sac: '0',
            },
            {
                name: 'Matt Ausloos',
                atBats: '4',
                runs: '2',
                hits: '1',
                doubles: '0',
                triples: '0',
                homeruns: '0',
                runsBattedIn: '1',
                baseOnBalls: '1',
                strikeouts: '0',
                sac: '0',
            },
            {
                name: 'Jon Keane',
                atBats: '3',
                runs: '2',
                hits: '3',
                doubles: '2',
                triples: '0',
                homeruns: '0',
                runsBattedIn: '1',
                baseOnBalls: '1',
                strikeouts: '0',
                sac: '1',
            },
            {
                name: 'Avery Goodman',
                atBats: '4',
                runs: '2',
                hits: '2',
                doubles: '0',
                triples: '0',
                homeruns: '0',
                runsBattedIn: '1',
                baseOnBalls: '0',
                strikeouts: '0',
                sac: '1',
            },
            {
                name: 'Josh Serio',
                atBats: '3',
                runs: '1',
                hits: '2',
                doubles: '1',
                triples: '0',
                homeruns: '1',
                runsBattedIn: '6',
                baseOnBalls: '0',
                strikeouts: '0',
                sac: '0',
            },
            {
                name: 'Kelly Goodman',
                atBats: '3',
                runs: '0',
                hits: '3',
                doubles: '0',
                triples: '0',
                homeruns: '0',
                runsBattedIn: '0',
                baseOnBalls: '1',
                strikeouts: '0',
                sac: '0',
            },
            {
                name: 'Donny Baseball',
                atBats: '4',
                runs: '1',
                hits: '3',
                doubles: '0',
                triples: '0',
                homeruns: '0',
                runsBattedIn: '1',
                baseOnBalls: '0',
                strikeouts: '0',
                sac: '0',
            },
            {
                name: 'Dennis Vavrik',
                atBats: '4',
                runs: '0',
                hits: '0',
                doubles: '0',
                triples: '0',
                homeruns: '0',
                runsBattedIn: '1',
                baseOnBalls: '0',
                strikeouts: '0',
                sac: '0',
            },
            {
                name: 'Jim Fuchs',
                atBats: '3',
                runs: '1',
                hits: '1',
                doubles: '0',
                triples: '0',
                homeruns: '0',
                runsBattedIn: '1',
                baseOnBalls: '0',
                strikeouts: '2',
                sac: '0',
            },
        ]
    }
]