export const players = [
  "Matt Ausloos",
  "Jason Fuchs",
  "Elijah Goodman",
  "Jon Keane",
  "Steve Nelsen",
  "Josh Serio",
  "Matt Goetz",
  "Kelly Goodman",
  "Avery Goodman",
  "Donny Baseball",
  "Jim Fuchs",
  "Rick Steinberg",
  "Dennis Vavrik",
  "Matthew Liewen",
  "Sam Botbol",
  "Bob 'Truth' Goetz",
];
